# 2020年02月03日 学习日记

花了些时间研究下了promise的源码[链接](https://github.com/then/promise)

现从我之前的疑惑开始聊起。我们都知道 new Promise() 返回一个Promise对象 假设这个对象叫p1
p1.then() 返回一个新的对象Promise。(这一点是为了链式调用的)

```
var p1 = new Promise(function (resolve,reject) {

})

var p2 = p1.then(function () {} , function () {})
```

p1的状态，通过resolve()函数使得p1的对象 转向到 resolve状态

#### 那么p2的状态是怎么做到的呢？

```
Promise.prototype.then = function(onFulfilled, onRejected) {
  // 假如 用户实现继承Promise后 new的对象
  if (this.constructor !== Promise) {
    return safeThen(this, onFulfilled, onRejected);
  }
  // 创建了一个新的promise noop空函数
  var res = new Promise(noop);
  handle(this, new Handler(onFulfilled, onRejected, res));
  return res;
};
```

这是源码里的then方法, 我们直接跳过if语句分之
可以看到 的确promise.then() 返回的是一个新的promise对象。
handle此时处理的是p1的状况 假设此时的p1的状态已经变成fullfilled状态。
handle(this , new Handler(onFulfilled, onRejected, res))
值得一提的是 **this指向的是p1**
```
// deferred就是new Handler对象
deferred = {
  onFulfilled:成功的callback,
  onRejected: 失败的callback,
  res: p2对象
}

function handle(self, deferred) {
  // 当then里的fullfilled 返回一个promise对象时
  while (self._i === 3) {
    self = self._j;
  }
  if (Promise._l) {
    Promise._l(self);
  }
  if (self._i === 0) {
    if (self._h === 0) {
      self._h = 1;
      self._k = deferred;
      return;
    }
    if (self._h === 1) {
      self._h = 2;
      self._k = [self._k, deferred];
      return;
    }
    self._k.push(deferred);
    return;
  }
  handleResolved(self, deferred);
}

```

可以跳过这些if语句 因为 此时self指向p1
假设p1的状态是 p1._i = 1 所以直接到handleResolved函数上(具体可以看 当调用了resolve()函数后的实际情景)

```
function handleResolved(self, deferred) {
  asap(function() {
    var cb = self._i === 1 ? deferred.onFulfilled : deferred.onRejected;
    // 假如 第一个promise的成功回调 是null
    if (cb === null) {
      if (self._i === 1) {
        resolve(deferred.promise, self._j);
      } else {
        reject(deferred.promise, self._j);
      }
      return;
    }
    var ret = tryCallOne(cb, self._j);
    if (ret === IS_ERROR) {
      reject(deferred.promise, LAST_ERROR);
    } else {
      resolve(deferred.promise, ret);
    }
  });
}

function tryCallOne(fn, a) {
  try {
    return fn(a);
  } catch (ex) {
    LAST_ERROR = ex;
    return IS_ERROR;
  }
}
```

也就是说p1 此时是fullfilled状态。 得执行then里的函数，通过asap() 放到微任务队列中。

那看到 var ret = tryCallOne(cb, self._j);
cb执行后返回结果ret，deferred.promise指向p2
再来看resolve函数
```
function resolve(self, newValue) {
  // Promise Resolution Procedure: https://github.com/promises-aplus/promises-spec#the-promise-resolution-procedure
  if (newValue === self) {
    return reject(
      self,
      new TypeError('A promise cannot be resolved with itself.')
    );
  }
  if (
    newValue &&
    (typeof newValue === 'object' || typeof newValue === 'function')
  ) {
    var then = getThen(newValue);  // 假如newValue.then是个function
    if (then === IS_ERROR) {
      return reject(self, LAST_ERROR);
    }
    if (
      then === self.then &&
      newValue instanceof Promise  // 假如newValue.then是个Promise对象
    ) {
      self._i = 3;
      self._j = newValue;
      finale(self);
      return;
    } else if (typeof then === 'function') {
      doResolve(then.bind(newValue), self);
      return;
    }
  }
  // newVal = null undefined boolean string number的情况下
  self._i = 1;
  self._j = newValue;
  finale(self);
}
```
这里兜兜转转 我们假设newValue 是个promise对象 直接说结论
**p2._i = 3;p2._j = promise**
再调用finale(self)

```
function finale(self) {
  if (self._h === 1) {
    handle(self, self._k);
    self._k = null;
  }
  if (self._h === 2) {
    for (var i = 0; i < self._k.length; i++) {
      handle(self, self._k[i]);
    }
    self._k = null;
  }
}
```

这里我们再假设有调用过p2.then() 也就是说 p2._h = 1;
还记得吗 p2._i = 3; p2._h = promise
再重新看handle()

```
// deferred就是new Handler对象
deferred = {
  onFulfilled:成功的callback,
  onRejected: 失败的callback,
  res: p2对象
}

function handle(self, deferred) {
  // 当then里的fullfilled 返回一个promise对象时
  while (self._i === 3) {
    self = self._j;
  }
  if (Promise._l) {
    Promise._l(self);
  }
  if (self._i === 0) {
    if (self._h === 0) {
      self._h = 1;
      self._k = deferred;
      return;
    }
    if (self._h === 1) {
      self._h = 2;
      self._k = [self._k, deferred];
      return;
    }
    self._k.push(deferred);
    return;
  }
  handleResolved(self, deferred);
}

```

结合我们到假设，代码运行到了while() 这一块
p2.\_i 不正等于3吗 p2._j = 新的promise对象
再返回来。原来整个p2 被替换了。

至此得出结论。promise.then()返回的promise对象 的状态 是由return值来决定的。

还有就是 ，其实 不管是new Promise() 也好 ，promise.then() 返回的promise也好

都是由某个语句设置 状态
那为什么 new Promise()要用 resolve() 这个函数呢？
其实很简单，你想啊 new声明 的对象 假如 Promise函数里 有return语句
返回的对象不就是 return值了吗。为了这一点，我觉得才采用了这种方式吧。